ALTER TABLE "RunwayClip" ALTER COLUMN "status" SET DEFAULT 'queued';

ALTER TABLE "RunwayClip" ADD COLUMN IF NOT EXISTS "queuePosition" INTEGER;
ALTER TABLE "RunwayClip" ADD COLUMN IF NOT EXISTS "submittedAt" TIMESTAMP(3);
ALTER TABLE "RunwayClip" ADD COLUMN IF NOT EXISTS "generationStart" TIMESTAMP(3);
ALTER TABLE "RunwayClip" ADD COLUMN IF NOT EXISTS "generationEnd" TIMESTAMP(3);
ALTER TABLE "RunwayClip" ADD COLUMN IF NOT EXISTS "downloadEnd" TIMESTAMP(3);
ALTER TABLE "RunwayClip" ADD COLUMN IF NOT EXISTS "muxEnd" TIMESTAMP(3);
ALTER TABLE "RunwayClip" ADD COLUMN IF NOT EXISTS "completedAt" TIMESTAMP(3);
ALTER TABLE "RunwayClip" ADD COLUMN IF NOT EXISTS "costUsd" DOUBLE PRECISION;
ALTER TABLE "RunwayClip" ADD COLUMN IF NOT EXISTS "errorMessage" TEXT;
ALTER TABLE "RunwayClip" ADD COLUMN IF NOT EXISTS "retryCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "RunwayClip" ADD COLUMN IF NOT EXISTS "runwayPollCount" INTEGER NOT NULL DEFAULT 0;

UPDATE "RunwayClip" SET "status" = 'queued' WHERE "status" = 'pending';
